### ISSUE TITLE
Stucks on mounting archives in vifm

### ISSUE THREAD

**Issue by thealio** [andrew-grechkin/fuse3-p7zip#8]
Hi
I'm trying fuse3-p7zip on Arch, using the AUR package.
I'm on virtualbox.
Iìs simply doesn' works, the vifm stuck mounting every kind of archive, stucking on an empty folder, from which you cannot escape, because it may be busy

**Comment by thealio** [comment]
I have this error on vifm

```
Critical error
  iconv  [84] : invalid or incomplete multibyte or wide character
                                                             
                              Press Return to continue

```
This time on bare metal
Plus, chautic-aur guys have this issue compiling
https://github.com/chaotic-aur/packages/issues/2442#issuecomment-1537547954

**Comment by andrew-grechkin** [comment]
This report is not enough to understand what is wrong.
If you see it in some log please provide full log and commands you have run.
It's better to do everything in command line and not use vifm for that (you need to limit number of involved apps to figure out the root cause)

I need a complete description how to reproduce the issue and probably I will also need an archive itself to try this. As I already told I don't see such issues on my side and for now I think that just archive is problematic.

As about the build issue - it's fixed already

**Comment by andrew-grechkin** [comment]
No reaction from issue reporter
